// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmDJLDSgpJgl0oi4mXMHxnX5ltdYxVaus',
    appId: '1:759519696680:web:5ab3f7ef7ccabf3837221d',
    messagingSenderId: '759519696680',
    projectId: 'riverpod-firebase-practice',
    authDomain: 'riverpod-firebase-practice.firebaseapp.com',
    storageBucket: 'riverpod-firebase-practice.appspot.com',
    measurementId: 'G-B3SX25FPXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG-dGiGqT0B0iMpuP2UPhPm5J8FIUnqcM',
    appId: '1:759519696680:android:cdafaf30e280721e37221d',
    messagingSenderId: '759519696680',
    projectId: 'riverpod-firebase-practice',
    storageBucket: 'riverpod-firebase-practice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyGj-YMlVqao_VplwgfyArUcqVMFxu9XA',
    appId: '1:759519696680:ios:91810eae21da945437221d',
    messagingSenderId: '759519696680',
    projectId: 'riverpod-firebase-practice',
    storageBucket: 'riverpod-firebase-practice.appspot.com',
    iosClientId: '759519696680-evcdotfirqkoa3j6fb539rsdbmvcjk3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodFirebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyGj-YMlVqao_VplwgfyArUcqVMFxu9XA',
    appId: '1:759519696680:ios:91810eae21da945437221d',
    messagingSenderId: '759519696680',
    projectId: 'riverpod-firebase-practice',
    storageBucket: 'riverpod-firebase-practice.appspot.com',
    iosClientId: '759519696680-evcdotfirqkoa3j6fb539rsdbmvcjk3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.riverpodFirebasePractice',
  );
}
